### ISSUE TITLE
Sodium disables this mod

### ISSUE THREAD

**Issue by compmalc** [dima-dencep/super-better-grass#11]
ive had this mod working with sodium just last night, i created a new instance and redownloaded mods because something unrelated wasnt working for me, but when i download this mod it works fine, then i pair is with sodium like how i did on my older instance, but it doesnt work! (both instances are on 1.21 btw, same loader same everything)

**Comment by compmalc** [comment]
tried downloading indium as well, just crashes my game when i try to join a world/server

**Comment by compmalc** [comment]
figured it out. latest version of fabric api breaks the mod with sodium and indium.

**Comment by Grandev-0** [comment]
Same
