### ISSUE TITLE
Crash with ModernFix dynamic resources

### ISSUE THREAD

**Issue by ImGRUI** [dima-dencep/super-better-grass#2]
Recently, MoreCulling has fixed issue with ModernFix dynamic resources crashing. But when I use it with SuperBetterGrass, Continuity and MoreCulling, I get this crash: https://mclo.gs/epJTZiy

**Comment by dima-dencep** [comment]
I'm using modernfix with sbg, everything is fine

**Comment by ImGRUI** [comment]
Please test with MoreCulling, sbg and continuity with dynamic resources on, there will be a crash. I was able to easily replicate it.

**Comment by ImGRUI** [comment]
Plus, it occurs on rebulding resources from sbg, so its probably sbg fault

**Comment by dima-dencep** [comment]
Just uninstall moreculling, they incorrectly fixed the bug.

**Comment by FxMorin** [comment]
Don't drag me into this. MoreCulling doesn't show up once in that stack trace.
Most likely continuity

**Comment by dima-dencep** [comment]
> MoreCulling doesn't show up once in that stack trace.

Then what's this?
![image](https://github.com/dima-dencep/super-better-grass/assets/66722732/645abab1-6c01-47cd-b702-4a30c271eeba)

**Comment by FxMorin** [comment]
Oh wait ya im blind.
However that's just a `getModel()` call which tons of mods do. So that better not be the cause

**Comment by dima-dencep** [comment]
If you remove moreculling, there is no crash.
So I'm going to say it's the problem.

**Comment by dima-dencep** [comment]
So I removed three mixins from the config and the crash disappeared, still denying it's your problem?
```patch
-    "models.cullshape.Deserializer_cullShapeMixin",
-    "models.cullshape.JsonUnbakedModel_cullShapeMixin",
-    "models.cullshape.ShapeCache_cullShapeMixin",
```

**Comment by FxMorin** [comment]
Ya except my mods works fine with ModernFix also. If I remove your mod it also fixes the problem.
This goes both ways

**Comment by FxMorin** [comment]
ModernFix should stop writing optimizations that break compatibility

**Comment by dima-dencep** [comment]
> If I remove your mod it also fixes the problem.

If you remove ANY mod from his modpack, the crash goes away

**Comment by dima-dencep** [comment]
If you haven't figured out why the problem is moreculling, it's because you're [trying to get the model too early](https://github.com/FxMorin/MoreCulling/blob/master/src/main/java/ca/fxco/moreculling/mixin/models/cullshape/ShapeCache_cullShapeMixin.java#L28) and coincidentally it's not loaded yet, and an NPE occurs inside the `getModel` method
