### ISSUE TITLE
Fancy grass option doesn't work with Sodium and Minecraft 1.20.6

### ISSUE THREAD

**Issue by xMelonekMaX** [dima-dencep/super-better-grass#4]

**Comment by dima-dencep** [comment]
I checked, it's working

**Comment by xMelonekMaX** [comment]
I tested on:
Fabric Loader 0.15.11
fabric-api-0.97.8+1.20.6.jar
cloth-config-14.0.126-fabric.jar
sodium-fabric-0.5.8+mc1.20.6.jar
SuperBetterGrass-1.5.2+1.20.1.jar

Grass blocks look the same in each option

**Comment by dima-dencep** [comment]
install indium

**Comment by CommandGenius** [comment]
Better snow does not work on 1.20.6.
