### ISSUE TITLE
Random grass blocks have no sides and the grass block item has no top texture or biome tint applied

### ISSUE THREAD

**Issue by slushieuwu** [dima-dencep/super-better-grass#9]
![image](https://github.com/dima-dencep/super-better-grass/assets/86991346/5556fee0-be95-45f6-afc9-0cbbb8298f77)

![image](https://github.com/dima-dencep/super-better-grass/assets/86991346/bc664607-c53b-46cd-893e-fa48fb2bc963)

**Comment by dima-dencep** [comment]
Do you have a better grass resourcepack?

**Comment by slushieuwu** [comment]
it happens even without any resource packs enabled

**Comment by slushieuwu** [comment]
if you need a log or anything, i can provide

**Comment by slushieuwu** [comment]
tested, does not happen in a clean instance, must be a mod incompatibility

**Comment by slushieuwu** [comment]
the tall grass item seems to also not be visible, for some reason
